task_instance: "mrqa, mlm4mrqa, match4mrqa"
target_tag: 1, 0, 0
mix_ratio: 1.0, 0.5, 0.5

save_path: "output_model/secondrun"

backbone: "ernie-en-uncased-large"
backbone_config_path: "../../pretrain/ernie-en-uncased-large/ernie_config.json"

vocab_path: "../../pretrain/ernie-en-uncased-large/vocab.txt"
do_lower_case: True
max_seq_len: 512

batch_size: 4
num_epochs: 0.1
optimizer: "adam"
learning_rate: 3e-5
warmup_proportion: 0.1
weight_decay: 0.1

print_every_n_steps: 1
